# Generated by Django 4.0.4 on 2022-07-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'permiso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tasacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('propiedad', models.CharField(max_length=50)),
                ('nombre_propietario', models.CharField(max_length=50)),
                ('rut_propietario', models.CharField(max_length=50)),
                ('documentacion', models.BinaryField()),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'tasacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tasador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tasador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=25)),
                ('correo', models.CharField(max_length=30)),
                ('telefono', models.FloatField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
